# This workflow attempts to compile LFS.

name: Test

# Controls when the workflow will run
on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Check requirements
      - name: Check for prerequisites
        run: sudo ./mylfs.sh -e
      
      # Enable verbose
      - name: Verbose logging
        run: sudo ./mylfs.sh -V
        
      # Clean pre-existing images
      - name: Clean image
        run: sudo ./mylfs -c
        
      # Build LFS
      - name: Build LFS
        run: sudo ./mylfs.sh -b
